# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: 'Build and deploy JAR app to Azure Web App: ecoaid-mvc-rm557540'

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '17'
    
    - name: Build with Maven
      run: mvn clean install
      env:
        MSSQL_HOST: ${{ secrets.AZURE_SQL_HOST }}
        MSSQL_PORT: ${{ secrets.AZURE_SQL_PORT }}
        MSSQL_DATABASE: ${{ secrets.AZURE_SQL_DATABASE }}
        MSSQL_USER: ${{ secrets.AZURE_SQL_USERNAME }}
        MSSQL_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with: 
        app-name: 'ecoaid-mvc-rm557540'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e20e72d6c5954d88a73659376d99915c }}
        package: '${{ github.workspace }}/target/*.jar'
